# See https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
dist: xenial

language: scala

addons:
  hostname: localhost

services:
  - docker

jdk:
  - openjdk8

scala:
  - "2.11.12"
  - "2.12.10"

before_cache:
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt            -name "*.lock"               -type f -delete
  - find $HOME/.coursier/cache -name "*.lock"               -type f -delete

cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.sbt
   - $HOME/.couriser

script:
  - .travis/run.sh

notifications:
  email:
    recipients:
      - gr.pomadchin@gmail.com
