version: "2.4"
services:
  server:
    image: geotrellis/geotrellis-pointcloud-server:latest
    ports:
      - "9000:9000"
    volumes:
      - ${PWD}/data:/app/data
      - ${PWD}/.aws/credentials:/root/.aws/credentials
    environment:
      # A PDAL setting, path to AWS credentials file:
      # https://github.com/connormanning/arbiter/blob/e9f91be5d7b36213e82bab86c1810f9bcc9225d3/arbiter/drivers/s3.cpp#L301
      - AWS_CONFIG_FILE=/root/.aws/credentials
    command: --public-url http://localhost:9000/
