version: "2.4"
services:
  server:
    image: geotrellis/geotrellis-pointcloud-server:latest
    ports:
      - "9092:9092"
    volumes:
      - ${PWD}/data:/app/data
    command: --public-url http://localhost:9000/
